baseURL = 'https://clcs-sustech.github.io/research-blog'
languageCode = 'en-us'
title = 'CLCS实验室研究札记 | CLCS Research Blog'

theme = 'archie'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 5 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "[计算语言学与意識科学实验室 | Computational Linguistics and Consciousness Science (CLCS) Lab](https://clcs-sustech.github.io)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/CLCS-SUSTech"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4